# Assume Python 3.12
target-version = "py39"
extend-exclude = ["alembic"]

[lint]
select = ["E", "F", "UP", "B", "SIM", "Q"]
ignore = ["F821","B008"]


fixable = ["ALL"]
unfixable = []


[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"
line-ending = "auto"

skip-magic-trailing-comma = false

docstring-code-format = false
docstring-code-line-length = "dynamic"