"""add field to movie

Revision ID: 04330c258cab
Revises: 7da27f3b8bb8
Create Date: 2025-08-08 13:00:43.871616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04330c258cab'
down_revision: Union[str, Sequence[str], None] = '7da27f3b8bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('video_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'video_path')
    # ### end Alembic commands ###
