name: Ruff-linter
on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    types:
      - opened
    branches:
      - 'main'
      - 'dev'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3